project_name: ld-find-code-refs

run:
  deadline: 120s
  tests: false

linters:
  enable-all: true
  disable:
      - golint
      - stylecheck
      - gochecknoglobals
      - lll
      - errcheck
      - interfacer
      - tagliatelle
      - varnamelen
      - nonamedreturns
      - nlreturn # re-enable this after fixing all cases
      - gomnd # re-enable this after fixing all cases
      - nosnakecase
      - ifshort # re-enable
      - nilerr #re-enable
      - goerr113
      - exhaustivestruct
      - exhaustruct
      - exhaustive
      - godot
      - wsl #fix
      - gocognit
      - revive
      - errname
      - cyclop
      - gofumpt # fix
      - gci
      - nestif # fix
      - gosec
      - gocritic
  fast: false

linter-settings:
  goimports:
    local-prefixes: github.com/launchdarkly,gopkg.in/launchdarkly

issues:
  exclude:
    - "G104: Errors unhandled." # Let errcheck handle these
    - "error returned from external package is unwrapped"
    - "error returned from interface method should be wrapped"
    # - "error is not nil (line 73) but it returns nil"
    - "SA5011: possible nil pointer dereference" # should fix
    - "comparing with == will fail on wrapped errors. Use errors.Is to check for a specific error" # should fix
    - "comparing with != will fail on wrapped errors. Use errors.Is to check for a specific error" # should fix
    - "non-wrapping format verb for fmt.Errorf. Use `%w` to format errors" # should fix
    - 'G307: Deferring unsafe method "Close" on type "*os.File"'
    - "calculated cyclomatic complexity for function processFileContent is 11, max is 10"
    - "unnecessary leading newline" # should fix
    - "unnecessary trailing newline" # fix
    - "append to slice `projectKeys` with non-zero initialized length"
    - "SA5011(related information): this check suggests that the pointer can be nil" # fix
  exclude-rules:
    # Exclude some `staticcheck` messages.
    - linters:
        - staticcheck
      text: "SA5011"
  
  exclude-use-default: false
  max-same-issues: 1000
  max-per-linter: 1000
