builds:
  - binary: ld-find-code-refs
    id: ld-find-code-refs
    main: ./cmd/ld-find-code-refs/
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
  - binary: ld-find-code-refs-github-action
    id: ld-find-code-refs-github-action
    main: ./build/package/github-actions/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - binary: ld-find-code-refs-bitbucket-pipeline
    id: ld-find-code-refs-bitbucket-pipeline
    main: ./build/package/bitbucket-pipelines/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: ld-find-code-refs
    builds:
      - ld-find-code-refs

nfpms:
  - id: ld-find-code-refs
    file_name_template: >-
      {{- .ProjectName -}}_
      {{- .Version -}}.
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end -}}
    homepage: https://launchdarkly.com/
    maintainer: LaunchDarkly <team@launchdarkly.com>
    description: Job for finding and sending feature flag code references to LaunchDarkly
    license: Apache 2.0
    vendor: LaunchDarkly
    formats:
      - deb
      - rpm

brews:
  - name: ld-find-code-refs
    ids:
      - ld-find-code-refs
    description: Job for finding and sending feature flag code references to LaunchDarkly
    homepage: "https://launchdarkly.com"
    repository:
      owner: launchdarkly
      name: homebrew-tap
      branch: main
      git:
        url: git@github.com:launchdarkly/homebrew-tap.git
        private_key: "{{ .Env.HOMEBREW_GH_TOKEN }}"
    folder: Formula
    url_template: "https://github.com/launchdarkly/ld-find-code-refs/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    install: |
      bin.install "ld-find-code-refs"
    commit_author:
      name: LaunchDarklyReleaseBot
      email: launchdarklyreleasebot@launchdarkly.com

release:
  disable: true # the release GHA takes care of releasing to Github

dockers:
  - image_templates:
      - "launchdarkly/ld-find-code-refs:latest"
      - "launchdarkly/ld-find-code-refs:{{ .Version }}"
    dockerfile: Dockerfile
  - goos: linux # GOARCH of the built binaries/packages that should be used.
    goarch: amd64
    ids:
      - ld-find-code-refs-github-action
    image_templates:
      - "launchdarkly/ld-find-code-refs-github-action:latest"
      - "launchdarkly/ld-find-code-refs-github-action:{{ .Version }}"
    dockerfile: Dockerfile.github
  - goos: linux # GOARCH of the built binaries/packages that should be used.
    goarch: amd64
    ids:
      - ld-find-code-refs-bitbucket-pipeline
    image_templates:
      - "launchdarkly/ld-find-code-refs-bitbucket-pipeline:latest"
      - "launchdarkly/ld-find-code-refs-bitbucket-pipeline:{{ .Version }}"
    dockerfile: Dockerfile.bitbucket
