repos:
- repo: https://github.com/golangci/golangci-lint
  rev: v1.18.0
  hooks:
  - id: golangci-lint
    name: golangci-lint
    description: Fast linters runner for Go.
    entry: golangci-lint run -D funlen -D bodyclose -D typecheck
    types: [go]
    language: golang
    pass_filenames: false

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.3.3
  hooks:
    - id: go-unit-tests
