name: Gosec
on:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  Gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: launchdarkly/gha-ld-gosec@v2
        with:
          aws-assume-role: ${{ secrets.ORG_SECURITY_GHA_ROLE_ARN }}
          s3-bucket: ${{ secrets.ORG_SECURITY_INVENTORY_BUCKET }}
